nano_folio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("web.urls",namespace="web"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web.views import category, index, contact, gallery


app_name = "web"

urlpatterns = [
    path("",index,name="index"),
    path("contact",contact,name="contact"),
    path("category/",category, name="category"),
    path("gallery/<pk>",gallery, name="gallery")
]

web/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=155)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]


class Gallery(models.Model):
    image = models.ImageField(upload_to="gallery/")
    category = models.ForeignKey("web.Category",on_delete=models.CASCADE)

    def __str__(self):
        return str(self.image)

    class Meta:
        ordering = ["id"]


class Contact(models.Model):
    name = models.CharField(max_length=155)
    email = models.EmailField(max_length=155)
    message = models.TextField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]


class About(models.Model):
    image = models.FileField(upload_to="about/")
    title = models.CharField(max_length=155)
    description = models.TextField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["id"]


class Address(models.Model):
    address = models.TextField(max_length=255)

    def __str__(self):
        return self.address

    class Meta:
        ordering = ["id"]

web/forms.py
from django.forms import ModelForm, fields, widgets
from web.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        widgets = {
            "name" : widgets.TextInput(attrs={
                "placeholder" : "Name"
            }),
            "email" : widgets.EmailInput(attrs={
                "placeholder" : "Email"
            }),
            "message" : widgets.Textarea(attrs={
                "placeholder" : "Message",
                "rows" : 5,
                "cols" : 30
            })
        }

web/views.py
import json
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render
from django.conf import settings

from web.models import About, Address, Category, Contact, Gallery
from web.forms import ContactForm


def index(request):
    category_name = request.GET.get("category")

    categories = Category.objects.all()
    galleries = Gallery.objects.all()
    contacts = Contact.objects.all()
    abouts = About.objects.get()
    addresses = Address.objects.all()
    form = ContactForm()

    context = {
        "categories" : categories,
        "galleries" : galleries,
        "contacts" : contacts,
        "abouts" : abouts,
        "addresses" : addresses,
        "form" : form,
        "MEDIA_URL" : settings.MEDIA_URL,
    }

    return render(request,"index.html",context=context)


def contact(request):
    form = ContactForm(request.POST)

    if form.is_valid():
        if not Contact.objects.filter(email=request.POST.get('email')).exists():
            form.save()

            response_data = {
                "status" : "success",
                "title" : "Successfully Registered",
                "message" : "You are Subscribed to the News Letter"
            }
        else:
            response_data = {
                "status" : "error",
                "title" : "Already Registered",
                "message" : "You are Already Subscribed to the News Letter,no need to Subscribe again"
            }
    else:
        response_data = {
                "status" : "error",
                "title" : "Your Form is Not Valid",
                "message" : "Your Form is Not Valid,Try again"
            }

    return HttpResponse(json.dumps(response_data),content_type="application/javascript")


def category(request):
    category_name = request.GET.get('category')

    print("###############################",category_name)
    if category_name:
        if category_name == "All":
            projects = Gallery.objects.all().values()
            data = list(projects)  
            response_data = {
                "title" : "success",
                "data" : data,
            }
        elif Category.objects.filter(name=category_name).exists():
            if Gallery.objects.filter(category__name=category_name).exists():
                projects = Gallery.objects.filter(category__name=category_name).values()
                data = list(projects)  

                response_data = {
                    "title" : "success",
                    "data" : data,
                }
            else:
                response_data = {
                    "title" : "failed",
                    "message" : "projects not found",
                }
        else:
            response_data = {
                "title" : "failed",
                "message" : "Category not found",
            }
    else:
        response_data = {
            "title" : "failed",
            "message" : "Category not found",
        }

    return JsonResponse({'response_data': response_data})


def gallery(request,pk):
    gallery = Gallery.objects.get(pk=pk)

    context = {
        "gallery" : gallery
    }

    return render(request,"gallery.html",context=context)

templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
</head>
<body>
    <h1 style="margin-bottom: 5%;font-weight: 900;text-align: center;">Gallery Image</h1>
    <div style="width: 80%;margin: 0 auto;border: 2px dotted rgb(5, 214, 241);padding: 2%;">
        <div style="width: 100%;">
            <img src="{{gallery.image.url}}" alt="" >
        </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
	<title>Nano-Folio</title>
	<link
    rel="icon"
    type="image/png' %}"
    sizes="32x32"
    href="{% static 'img/favicon.ico' %}"
    />
</head>
<body>
	<section id="spotlight">
		<section class="wrapper">
			<div class="contents">
				<div class="heart-shape">
					<span>&#10084;</span>
				</div>
				<h1>Nano Folio</h1>
			</div>
		</section>
	</section>

    <section id="about">
        <section class="wrapper">
            <div class="container">
                <div class="left">
                    <div class="icon">
                        <img src="{{abouts.image.url}}" alt="Image" />
                    </div>
                    <h3>
                        {{abouts.title}}
                    </h3>
                </div>

                <div class="right">
                    <p>
						{{abouts.description}}
                    </p>
                </div>
            </div>
        </section>
    </section>

	<section id="gallery">
		<section class="wrapper">
		  <div class="top">
			<ul>
				{% for category in categories %}
					<li>
						<a href="{% url 'web:category' %}?category={{category.name}}">{{category.name}}</a>
					</li>
				{% endfor %}
				<li>
					<a href="{% url 'web:category' %}?category=All">All</a>
				</li>
				</ul>
		  </div>
		<div class="bottom">
			{% for gallery in galleries %}
			<div class="frame">
				<a href="{% url 'web:gallery' pk=gallery.pk %}" >
					<img src="{{gallery.image.url}}" alt="Image" />
				</a>
			</div>
			{% endfor %}
		  </div>
		</section>
	  </section>

	  <footer>
		<section class="wrapper">
			<form action="{% url 'web:contact' %}" method="post" class="ajax">
				{% csrf_token %}
				{{form.name}}
				{{form.email}}
				{{form.message}}
				<input type="submit" value="send" />
			</form>
			<div class="middle">
				<p class="paragraph">
					120 curabitor sed tortur ultrices,congue odio eget,poseuro urna.prasent at rhonscus 1980.
				</p>
				<p class="tel">
					Tel:010-020-0340
				</p>
				<ul>
					<li class="social">
						<a href="#" >
							<img src="{% static 'img/facebook-brands.svg' %}" alt="Social Media">
						</a>
					</li>
					<li class="social">
						<a href="#" >
							<img src="{% static 'img/twitter-brands.svg' %}" alt="Social Media">
						</a>
					</li>
					<li class="social">
						<a href="#" >
							<img src="{% static 'img/instagram-brands.svg' %}" alt="Social Media">
						</a>
					</li>
				</ul>
			</div>
			<div class="right">
				<div class="img_container">
					<img src="{% static 'img/searchengin-brands.svg' %}" alt="Lens">
				</div>
				<p>Contact</p>
			</div>
		</section>
		<p class="footer">
			Copyright 2020 Nano Folio  - Design Tooplate
		</p>
		
	</footer>

	<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
	<script>
		var MEDIA_URL = "{{MEDIA_URL}}"
		$('#gallery .top a').on('click', function(e){
			e.preventDefault();
			console.log("sfjbdkfjsjfb");
			var $this = $(this);
			var url = $this.attr("href")

			$.ajax({
				type:"GET",
				url:url,
				data: $(this),
				success: function(data) {
					console.log(data);
					var r_data = data.response_data.data
					console.log(r_data)
					let html_data = ""
					r_data.forEach((gallery) => {
						html_data += `<div class="frame"><img src="${MEDIA_URL}/${gallery.image}" alt="Image" /></div>`
					})
					$("#gallery .bottom").html(html_data)
				},
				failure: function(data) { 
					alert('Got an error dude');
				},
				processData:false,
				contentType:false,
				cache:false,
			})
		});
	</script>
</body>
</html>